# Generated by Django 2.2.6 on 2019-11-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=60)),
                ('paragraph', models.TextField(blank=True, db_index=True)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('image', models.CharField(blank=True, db_index=True, max_length=60)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=60)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('image', models.CharField(blank=True, db_index=True, max_length=60)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(db_index=True, max_length=60)),
                ('text', models.TextField(blank=True, db_index=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
